### ISSUE TITLE
Question about google IDP

### ISSUE THREAD

**Issue by jprivillaso** [qalshakhoori/sls-custom-cognito#1]
Hi, 
I would like to know how to fill in the information provided inside `ProviderDetails`.
Where can I find this information. 

You don't pass this information ay any place. How does it work ? 
I'm working with pure Cloudformation stacks so I'm wondering how to pass this info

Here's what I have:

```
CustomDomainCreator:
    Type: Custom::CustomDomainCreator
    Properties:
      ServiceToken: !GetAtt GoogleIdpLambdaFunction.Arn
      UserPoolId: !Ref UserPoolId
      ProviderName: Google
      ProviderType: Google
      Client_id: 'client_id'
      Client_secret: 'client_secret'
      Authorize_scopes: 'profile,email,openid'
```
